### ISSUE TITLE
Cannot set `mainfont` and `sansfont` for xelatex

### ISSUE THREAD

**Issue by huyhoang8398** [Wandmalfarbe/pandoc-latex-template#206]
- OS: Archlinux
- pandoc 2.11

Installed texlive-most, texlive-core, adobe sans font
```yaml
mainfont: "Source Sans Pro"
sansfont: "Source Sans Pro" 
```
```bash
> kpsewhich sourcesanspro.sty
/usr/share/texmf-dist/tex/latex/sourcesanspro/sourcesanspro.sty
```
Howerver, if I use default engine with 
```yaml
fontfamily: "sourcesanspro"
```
It changed the body font but not the tittle and header

**Comment by Wandmalfarbe** [comment]
Related Issue #69

**Comment by huyhoang8398** [comment]
you can use
```yaml
mainfont: "NewComputerModern"
sansfont: "NewComputerModern"
monofont: "JetBrains Mono"
```
![image](https://user-images.githubusercontent.com/25379882/145715148-4302a57b-cda6-4780-9c03-6e02c53f9c78.png)

**Comment by huyhoang8398** [comment]
Update 21/7/2022
On ubuntu, you can install `fonts-cmu` which has latin modern fonts
and in the yml
```yml
mainfont: "Latin Modern Roman"
sansfont: "Latin Modern Roman"
monofont: "JetBrains Mono"
```
![image](https://user-images.githubusercontent.com/25379882/180225727-53aa04e2-d54e-4072-bc8c-24b31cf30155.png)
