### ISSUE TITLE
Question: Adjust titlepage layout with Custom Template Variables

### ISSUE THREAD

**Issue by ibayer** [Wandmalfarbe/pandoc-latex-template#247]
Thanks for this great template. The pdfs in produce with default settings is amazing.

However, I run into two minor challenges with the title page layout in combination with the provided backgrounds.

![image](https://user-images.githubusercontent.com/1497140/125269757-4d898100-e309-11eb-8946-77861123915f.png)

The images has been created by modifying `pandoc-latex-template/examples/title-page-logo/document.md`.

```yml
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
lang: "en"
titlepage: true
titlepage-text-color: "7137C8"
titlepage-rule-color: "7137C8"
titlepage-rule-height: 2
logo: "logo.pdf"
logo-width: 30mm
titlepage-background: "../page-background/backgrounds/background11.pdf"
...
```

## Q1 Can the text spacing or position be adjusted to just move the date a little bit up or to the right?

![image](https://user-images.githubusercontent.com/1497140/125270442-f7690d80-e309-11eb-9a20-397de25717ad.png)

```yml
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: "2017-02-20"
subject: "Markdown"
keywords: [Markdown, Example]
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
lang: "en"
titlepage: true
titlepage-text-color: "7137C8"
titlepage-rule-color: "7137C8"
titlepage-rule-height: 2
logo: "logo.pdf"
logo-width: 30mm
titlepage-background: "../page-background/backgrounds/background4.pdf"
...
```

## Q2 Can the logo position be adjusted?

I understand that both layout issue can be address by changed the background pdf or digging into the latex code, however I was wondering if this Q1 &Q2 could also be addressed using `Custom Template Variables`. Any points are welcome. :)
