### ISSUE TITLE
urlcolor RGB Support

### ISSUE THREAD

**Issue by aress31** [Wandmalfarbe/pandoc-latex-template#299]
I do not understand why `rgb` is not supported for the `urlcolor` option. Trying to set a custom color using:

```yaml
urlcolor: "FDBDA4"
```

But getting error:

```
Error producing PDF.
! Package xcolor Error: Undefined color `FDBDA4'.
```

Any help will be welcome!

EDIT: Tried as a workaround to define a custom colour and then set it as follows:

```yaml

titlepage-text-color: "offWhite"

header-includes:
  - \definecolor{offWhite}{HTML}{EEEEEE}
```

But still getting an error...
