### ISSUE TITLE
CSL Citations Rendering but not in expected CSL format

### ISSUE THREAD

**Issue by williamcroberts** [Wandmalfarbe/pandoc-latex-template#313]
Hello,

I am using pandoc version 2.19.2 I have enabled option `--citeproc` and filter `citations`, see the command example below.

My issue is that references always render as `[@foo]` no matter what CSL is used. I am expecting that the reference be numerical in nature, something like `[1]`. However, The generated references section is in the expected format. I am using CSL `transactions-on-computer-systems.csl` as found here:
  - https://www.zotero.org/styles/transactions-on-computer-systems

Does anyone know why it's not working or things to try and trouble shoot it?

My YAML meta data block is as follows:
```md
---
title: "My Spec"
type: SPECIFICATION
status: DRAFT
bibliography: citations.yaml
csl: transactions-on-computer-systems.csl
...

foo bar example: [@fenner].

# References
```

With the following citations.yaml file:
```yaml
references:
  - id: fenner
    title: One-click science marketing
    author:
      - family: Fenner
        given: Martin
    container-title: Nature Materials
    volume: 11
    URL: "https://dx.doi.org/10.1038/nmat3283"
    DOI: 10.1038/nmat3283
    issue: 4
    publisher: Nature Publishing Group
    page: 261-263
    type: article-journal
    issued:
      year: 2012
      month: 3
```

Command Example:
```bash
	pandoc \
		--citeproc \
		--embed-resources \
		--standalone \
		--template=eisvogel.latex \
		--filter=mermaid-filter \
		--filter=pandoc-crossref \
		--resource-path=.:/resources \
		--data-dir=/resources \
		--top-level-division=section \
		--variable=block-headings \
		--variable=numbersections \
		--variable=table-use-row-colors \
		--metadata=date-english:"${DATE_ENGLISH}" \
		--metadata=year:"${YEAR}" \
		--metadata=titlepage:true \
		--metadata=titlepage-background:/resources/img/cover.png \
		--metadata=logo:/resources/img/my.png \
		--metadata=titlepage-rule-height:0 \
		--metadata=colorlinks:true \
		--metadata=contact:admin@trustedcomputinggroup.org \
		--from=markdown+implicit_figures+table_captions+citations \
		${extra_pandoc_options} \
		--to=pdf \
		"${build_dir}/${input_file}.3" \
		--output="${pdf_output}"
```

Pandoc Version Info
```bash
pandoc --version
pandoc 2.19.2
Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
citeproc 0.8.0.1, ipynb 0.2, hslua 2.1.0
Scripting engine: Lua 5.3
User data directory: /home/user/.local/share/pando
```
