### ISSUE TITLE
boxes-with-pandoc-latex-environment-and-awesomebox question

### ISSUE THREAD

**Issue by hrylandvest** [Wandmalfarbe/pandoc-latex-template#346]
Apologies for asking such a basic question, I'm still in learning mode with pandoc/latex.

In the example section, to in order to utilize boxes-with-pandoc-latex-environment-and-awesomebox, I assume that the following are the steps to utilize this feature:

1. Install pandoc-latex-environment `$ pip install pandoc-latex-environment`
2. Add` \usepackage{awesomebox}` to the eisvogel.tex template file. Where should this go exactly in the file?
3. Reconfigure the callout syntax in my obsidian.md file to the syntax shown:

```
::: note
Lorem ipsum dolor ...
:::
```
4. Run the pandoc command to convert replacing "document" and path to template with my values
  `pandoc "document.md" -o "document.pdf" --from markdown --template "../../eisvogel.tex" --filter pandoc-latex-environment --listings`

The above steps produce only the text and no callout syntax in the pdf. I'm obviously doing something wrong here. Would someone be so kind as to point me in the right direction?

**Comment by ndmalc** [comment]
I also had some difficulties to make it work as the documentation is very sparse on this one.

I think you did everything right except at the step 2. where based on the example [here](https://raw.githubusercontent.com/enhuiz/eisvogel/master/examples/boxes-with-pandoc-latex-environment-and-awesomebox/boxes.md), you should add the following in the YAML metadata block of your markdown file.

```
header-includes:
- |
  ` ``{=latex}
  \usepackage{awesomebox}
  ` ``
pandoc-latex-environment:
  noteblock: [note]
  tipblock: [tip]
  warningblock: [warning]
  cautionblock: [caution]
  importantblock: [important]
```
_Note: in the code block above, I did not found how to properly escape the \` characters so I added a space within the three \` that needs to be removed when copying_
