### ISSUE TITLE
Changing Color and Size of text in YAML Metadata block

### ISSUE THREAD

**Issue by dadlMilestone** [Wandmalfarbe/pandoc-latex-template#353]
Hello, I am attempting to change the size and color of fonts on the title page. 

- I would like to change the color of the subtitle and preferably use a hex value for the color. 
- I would like to change the size of the font for the title to be larger than the rest of the text on the title page.
- I would also like to put my title on multiple lines.

Here is a copy of my YAML:

```yaml
---
author: [Company Name]
titlepage: true
titlepage-text-color: "E6EDF3"
titlepage-rule-color: "EBD908"
titlepage-background: "pandoc/title.jpg"
toc: true
toc-own-page: true
header-includes: |
    \usepackage{sectsty}
    \sectionfont{\clearpage}
title: |
  Document
  Title
  Multiple
  Lines
subtitle: "SUBTITLE TEXT"
date: "EN v1.0"
footer-left: "Company Name - Document Title"
...
```
I have tried to change the title text by changing the title section of the yaml like so:

```yaml
title: |
  {\Huge Document}
  {\Huge Title}
  {\Huge Multiple}
  {\Huge Lines}
```

I have tried to change the textcolor using:

```yaml
subtitle: "\textcolor{yellow}{SUBTITLE TEXT}"
```

Neither seems to work how I'd like, and I would love to get this figured out, but also to get some knowledge about how and where I can use LaTeX commands in order to modify the title page.

The error I have been getting is:

```
[2023-07-24T23:01:28.177Z] Error producing PDF.
[2023-07-24T23:01:28.179Z] ! Too many }'s.
[2023-07-24T23:01:28.179Z] l.384 }
```

Please let me know if I've left out any pertinent information!!

Thanks!
