### ISSUE TITLE
Captions not working in default configuration with Docker image ?

### ISSUE THREAD

**Issue by rguyennot** [Wandmalfarbe/pandoc-latex-template#363]
Hi, 

After multiple tries, `captions` seems to not working in my case.

Below, my configuration : 

```yaml
---
title: "TITLE"
subtitle: "Subtitle"
lang: "en"
date: "2023-10-06 / Version 0.1.0"
book: true
keywords: [Markdown]
toc: true
toc-own-page: true
colorlinks: true
header-includes:
- |
  '''{=latex}
  \usepackage{tcolorbox}

  \newtcolorbox{info-box}{colback=cyan!5!white,arc=0pt,outer arc=0pt,colframe=cyan!60!black}
  \newtcolorbox{warning-box}{colback=orange!5!white,arc=0pt,outer arc=0pt,colframe=orange!80!black}
  \newtcolorbox{error-box}{colback=red!5!white,arc=0pt,outer arc=0pt,colframe=red!75!black}
  '''
pandoc-latex-environment:
  tcolorbox: [box]
  info-box: [info]
  warning-box: [warning]
  error-box: [error]
...
```

My Markdown test file using example from [examples/images-and-tables](https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master/examples/images-and-tables) 
```yaml
## Image with Caption - Issue

![Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.](images/tests/image.png)
```

In the final PDF rendering, the image caption does not appear...

The rendered PDF file  :  [2023-10-10_testing.pdf](https://github.com/Wandmalfarbe/pandoc-latex-template/files/12857885/2023-10-10_testing.pdf)

The Docker command I use to generate PDF files : 

```bash
docker run \
    --rm \
    --volume "$(pwd):/data" \
    --user $(id -u):$(id -g) \
    pandoc/extra:latest-alpine 999_tests.md \
    -o pdf/"$(date +%F)"_testing.pdf \
    -f markdown-implicit_figures \
    --template "./eisvogel.tex" \
    --highlight-style breezedark \
    --toc \
    -N \
    -V classoption=oneside \
    -V caption-justification=centering \
    --filter pandoc-latex-environment
```
