### ISSUE TITLE
Display "Page X of Y" in footer?

### ISSUE THREAD

**Issue by mrichman** [Wandmalfarbe/pandoc-latex-template#381]
How can this be done?

**Comment by rphsantos** [comment]
This is what I use in my properties to get page numbers:

```yaml
header-includes: 
- \usepackage{lastpage}
footer-left: "\\thepage \\hspace{1pt} / \\pageref*{LastPage}"
```
