### ISSUE TITLE
unicode characters not supported

### ISSUE THREAD

**Issue by monperrus** [Wandmalfarbe/pandoc-latex-template#420]
unicode characters such as Greek letters (α, β, γ, δ, etc.) are not supported.

> ! LaTeX Error: Unicode character β (U+03B2)
>              not set up for use with LaTeX.

a possible solution would be to use [DeclareUnicodeCharacter.sty](https://github.com/monperrus/DeclareUnicodeCharacter.sty), I've done it locally.

**Comment by Wandmalfarbe** [comment]
You can use XeTeX or LuaTeX as a Unicode aware engine that supports Unicode in the source document without additional packages or commands. Just compile your document with `--pdf-engine xelatex` or `--pdf-engine lualatex`.

It may be possible that some letters are still missing because of the default font Source Sans Pro that is used via LaTeX package [`sourcesanspro`](https://ctan.org/tex-archive/fonts/sourcesanspro). That package was last updated in 2020 and uses the version 3.006 of the font. You can use the latest version (now named Source Sans 3) by downloading the [TTF files on GitHub](https://github.com/adobe-fonts/source-sans/releases) and specifying it as a `mainfont`.

I also added an example [`font-unicode-font-fallback`](https://github.com/Wandmalfarbe/pandoc-latex-template/tree/master/examples/font-unicode-font-fallback) for fallback fonts with LuaTeX. You can display characters that are not supported in a certain font by specifying a fallback font (e.g. [Noto Sans Egyptian Hieroglyphs](https://fonts.google.com/noto/specimen/Noto+Sans+Egyptian+Hieroglyphs)).

```yml
---
mainfont: "Source Sans 3"
mainfontfallback:
  - "Noto Sans Oriya:"
  - "Noto Sans Myanmar:"
  - "Noto Sans Cuneiform:"
  - "Noto Color Emoji:mode=harf"
  - "Noto Sans Egyptian Hieroglyphs:"
...
```
