### ISSUE TITLE
TOC pages have no header and footer.

### ISSUE THREAD

**Issue by lutz** [Wandmalfarbe/pandoc-latex-template#77]
Hello,
I'm just trying out the template. But if I apply the following settings to the book example:
```yaml
titlepage: true
book: true
toc: true
toc-own-page: true
titlepage-color: "D8DE2C"
titlepage-text-color: "000000"
classoption: "oneside"
top-level-division: "chapter"
lang: "de-DE"
```
a table of contents is created, but it has neither the same header nor the same footer.

Best regards
Daniel
