### ISSUE TITLE
Source Sans Pro isn't applied as a main font family when using XeLaTeX

### ISSUE THREAD

**Issue by iandol** [Wandmalfarbe/pandoc-latex-template#8]
Hi, if I supply a `lang: en-GB` or `lang: en-US` metadata field to your custom-titlepage example, the main body text is not source sans pro any more, but the latex default:

![screen shot 2017-05-31 at 17 16 25](https://cloud.githubusercontent.com/assets/153905/26625268/2e1d7a9e-4626-11e7-971d-dd2c1effbecb.png)

removing it and all is fine...

```yaml
---
title: "Vinaque sanguine metuenti cuiquam Alcyone fixus"
author: [Author Name]
date: 2017-02-20
subject: "Markdown"
tags: [Markdown, Example]
subtitle: "Aesculeae domus vincemur et Veneris adsuetus lapsum"
titlepage: true
titlepage-color: eeeeee
titlepage-text-color: ffffff
titlepage-rule-color: ffffff
titlepage-rule-height: 1
lang: en-GB
...
```
